config/routes.rb
=> add_routes-1

Gemfile, Gemfile.lock, config/unicorn.rb
Gem「unicorn」の追加
unicorn.rbの編集
＃WHY
デプロイに向けての準備。
（EC2にGitからクローンするためPullRequest）
=> add_unicorn_deploy

config/database.yml
=> deploy_edit_dbyml

config/application.rb, config/database.yml
deviseについて修正
本番環境でのデータサーバ構築の際のエラー解決のため
=> deploy_edit_app.rb

Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, config/environments/production.rb, config/unicorn.rb
自動デプロイのため、capistranoの追加とファイルの修正。
=> add_capistrano

Gemfile
gemの編集。
- deviseを移動（development→外へ。試し）
- FontAwesomeの追加。
=> edit_gemfile

Gemfile
=> edit_gemfile2

app/assets/stylesheets/reset.scss, app/assets/stylesheets/sign_in.scss, app/views/devise/sessions/new.html.haml
=> [WIP]Add devise

app/controllers/application_controller.rb, config/database.yml, config/deploy.rb, config/deploy/production.rb
Basic認証の導入：本番環境のみで適用
コピーサイトの為、閲覧制限をかける必要性があり実装。
=> add_BasicAuthentication

app/assets/stylesheets/_aside.scss, app/assets/stylesheets/_footer.scss, app/assets/stylesheets/_pickup-item.html.scss, app/assets/stylesheets/index.scss, app/views/items/index.html.haml, app/views/shared/_aside.html.haml, app/views/shared/_footer.html.haml, app/views/shared/_pickup-item.html.haml
#WHAT
indexのビュー画面および、部分テンプレート画面追加
#WHY
font-awesome等が必要になったため一度マージ希望
=> Edit index view

app/assets/stylesheets/application.scss, app/assets/stylesheets/config/_mixin.scss, app/assets/stylesheets/config/_variable.scss, app/assets/stylesheets/items/_new.scss, app/controllers/application_controller.rb, app/controllers/items_controller.rb, app/models/brand.rb, app/models/category.rb, app/models/item.rb, app/views/items/new.html.haml, db/migrate/20190911092619_create_items.rb, db/migrate/20190911115605_create_categories.rb, db/migrate/20190911115856_create_brands.rb, db/migrate/20190911120828_add_details_to_items.rb, db/schema.rb, spec/factories/brands.rb, spec/factories/categories.rb, spec/factories/items.rb, spec/models/brand_spec.rb, spec/models/category_spec.rb, spec/models/item_spec.rb
出品ページ途中
Item, Category, Brandのテーブルを作成
modelファイルのアソシエーションはまだ
=> [WIP]商品出品ページ(その２)

app/assets/stylesheets/_item-user_footer.scss, app/assets/stylesheets/_step1.scss, app/assets/stylesheets/config/_mixin.scss
=> edit_scss-error

app/assets/stylesheets/application.scss, app/assets/stylesheets/users/logout.scss, app/assets/stylesheets/users/show.scss, app/controllers/users_controller.rb, app/views/users/logout.html.haml, config/routes.rb
#WHAT
ログアウト画面のマークアップ作成
#WHY
サーバーサイド記述に向けてのフロント作成
一時的にルーティング、コントローラの記述あり。
実装画像添付します。
https://gyazo.com/08e332a55c96a8300032dfb72c1f2199
=> ログアウト画面マークアップ作成。ページ移動に関する記述を一時的に作成。

app/uploaders/image_uploader.rb, config/initializers/carrierwave.rb
画像アップロードの分岐について修正、追記
- 本番：AWS使用
- 開発：public/uploades
- テスト：処理自体をスキップ
=> 画像保存先の分岐文修正

app/uploaders/image_uploader.rb, config/deploy.rb, config/initializers/carrierwave.rb
自動デプロイ時のエラー解決のため
一度S3での記述変更箇所をコメントアウトして検証します。
=> 自動デプロイ検証_分岐前に修正

Gemfile, Gemfile.lock
=> パンくずのgem追加

config/routes.rb
レビュー見過ごしorコンフリクト修正時に発生した、ルーティング設定で入れ子状に変わってしまっている部分の修正。
=> edit_routes.rb

app/assets/stylesheets/_breadcrumbs.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/items/_edit.scss, app/assets/stylesheets/items/_header2.scss, app/assets/stylesheets/mypage/_index.scss, app/assets/stylesheets/users/_logout.scss, app/assets/stylesheets/users/mypage_detailes.scss, app/views/items/index.html.haml, app/views/items/show.html.haml, app/views/mypage/identification.html.haml, app/views/mypage/index.html.haml, app/views/mypage/logout.html.haml, app/views/shared/_breadcrumbs.html.haml, app/views/shared/_header2.html.haml, config/breadcrumbs.rb
#WHAT
パンくず実装
#WHY
現状で実装できる画面まで追加済み
https://gyazo.com/20bee886be3080796d1e2235ca7042b8
https://gyazo.com/9340547b598f82d80b66f1976178f2e6
=> Add breadcrumb

app/assets/stylesheets/index.scss, app/assets/stylesheets/items/_item-box.scss, app/assets/stylesheets/items/_show.scss, app/assets/stylesheets/sign_up/_sign_in.scss, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/show.html.haml, app/views/shared/_item-box.html.haml
#WHAT
商品詳細ページの実装
及び商品イメージが関わるビューの調整
#WHY
商品詳細ページを実装し、購入画面へとリンクを作るため
確認画面の添付をいたします。
https://gyazo.com/4f2dcddbc8e6d37cd37b9116f58cdb3e
https://gyazo.com/eeab35c2803b8617c7bf70c2371fb1aa
=> Edit items show

app/assets/stylesheets/items/_show.scss, app/controllers/items_controller.rb, app/views/items/show.html.haml, app/views/shared/_item-box.html.haml, db/schema.rb
#WHAT
アイテム削除機能の実装
#WHY
アイテム詳細ページにて条件分岐でリンクの表示
出品ユーザーが自身のアイテムを削除できるよう実装
確認画像を添付いたします。
https://gyazo.com/63344b81e099d850849d40f904de6f0f
https://gyazo.com/543654e691226310aeddee6f85d31e6f
=> Edit destroy

app/assets/javascripts/item.js, app/assets/stylesheets/items/_show.scss, app/views/items/buy.html.haml
#WHAT
商品詳細ページのサムネイル画像切り替え
#WHY
JSファイル追加
全商品をメイン画面で表示可能にするため
確認画像添付いたします。
https://gyazo.com/9acd04000ad1f1260dbd9e8cc278837f
=> Add js item show

app/assets/stylesheets/items/_item-box.scss, app/views/shared/_item-box.html.haml
#WHAT
item_boxのcss修正
#WHY
hover追加・スペルミスの修正
business_statusによる条件分岐は未実装
=> indexアイテム写真にhover追加・クラス名のスペルミス修正

app/assets/javascripts/brand.js, app/assets/javascripts/category.js, app/assets/stylesheets/items/_new.scss, app/views/items/edit.html.haml, app/views/items/new.html.haml, db/seeds/category.rb
商品編集、出品機能の調整
・サイズとブランドのボックスをカテゴリーによって表示の有無を切り替えている。
・カテゴリーのseedファイルの追記
動作を本物に近づけるため
=> [WIP]商品編集、出品機能2

app/assets/stylesheets/config/_mixin.scss, app/assets/stylesheets/items/_item-box.scss, app/assets/stylesheets/items/_show.scss, app/views/items/show.html.haml, app/views/shared/_item-box.html.haml
商品を購入した時の「SOLD」を表示させるように変更。
itemのindexとshowのページに実装。
=> [WIP]SOLDの表示

app/assets/javascripts/category_drop.js, app/assets/stylesheets/items/_header2.scss, app/views/shared/_header3.html.haml
トップページのカテゴリ検索のドロップダウンリストを実装。
https://gyazo.com/dd93df352a7ad29af8091dd6af9a3067
=> Add dropdown

app/controllers/users/registrations_controller.rb
=> 自動デプロイエラー解決のため

db/migrate/20191001083952_drop_credit_cards.rb, db/schema.rb
以前のカードテーブルのマイグレーションファイルの消し忘れ対応。
クレジットカード→削除
カード→存在
=> drop_credit-table

app/assets/javascripts/brand.js, app/assets/stylesheets/items/_header2.scss, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/index.html.haml, app/views/shared/_header3.html.haml, db/seeds/category.rb
indexページの修正。
・カテゴリー、ブランドごとに表示が振り分けられるように、かつ、コントローラー内の記述量を少なくした。
・画面のサイズが小さくなっても、ヘッダーが崩れないように。
=> indexページの修正

app/assets/javascripts/payjp.js, app/assets/stylesheets/users/mypage_detailes.scss, app/controllers/purchase_controller.rb, app/views/purchase/show.html.haml
カード登録時のjsの動作に関して、ターボリンクス修正。
（他ページは微調整、コメントアウトの修正のみ）
=> Edit card-oage

app/controllers/card_controller.rb, app/views/mypage/profile.html.haml
コントローラ内のリダイレクトのpathを修正。
本番環境で登録完了に飛べない原因を探るため。
また、併せてプロフィールでrenderしていたheaderが旧バージョンで併せて修正。
=> Fix card show

app/controllers/card_controller.rb
本番キーを取得できていなかた可能性大。
キーの呼び出しを修正。
=> fix_card-controller

app/controllers/purchase_controller.rb
=> fix_purchase-conroller

app/assets/stylesheets/items/_show.scss, app/views/items/show.html.haml
=> 購入済商品のビュー変更

app/assets/javascripts/image_drop.js
隠していたイメージの投稿フォームに触ることができる状態になっていたので、修正。
=> 画像投稿フォーム修正

app/assets/stylesheets/items/_header2.scss
=> トップページのビュー修正

app/uploaders/image_uploader.rb, app/views/layouts/application.html.haml
二箇所のファイルで微調整。
- スライダーのターボリンクスの読み込み不具合
- イメージアップロードに関する設定調整
=> Fix ページ微調整

app/views/items/search.html.haml
Reverts wat310/freemarket_sample_58d#85
=> Revert "エラー解消"

app/views/mypage/index.html.haml
マイページのフッターをカメラに変更。
先ほどの手動リバートで忘れていました。
=> [WIP]マイページのフッターをカメラに変更

app/assets/stylesheets/application.scss, app/assets/stylesheets/items/_search.scss, app/assets/stylesheets/sign_up/_step1.scss, app/controllers/application_controller.rb, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/search.html.haml, app/views/shared/_header.html.haml, config/routes.rb
Add search のリバートをリバートをして修正が加えられた状態に戻しました。
Reverts wat310/freemarket_sample_58d#87
=> [WIP]Revert "Revert "Add search""

app/views/items/search.html.haml
検索でのheaderの変え忘れのリバートのリバート。
これで修正が加えられた状態に。
=> [WIP]Revert "Revert "エラー解消""

app/assets/stylesheets/sign_up/_sign_up.scss, app/assets/stylesheets/sign_up/_step1.scss, app/views/devise/registrations/new.html.haml, app/views/devise/sessions/new.html.haml, spec/controllers/card_controller_spec.rb, spec/controllers/purchase_controller_spec.rb, spec/factories/users.rb, spec/helpers/purchase_helper_spec.rb, spec/models/address_spec.rb, spec/models/card_spec.rb, spec/models/profile_spec.rb, spec/models/user_spec.rb
サインアップ画面のメールアドレスのボタンの不具合修正。
余白部分を押しても画面遷移するように。
ついでにテスト用のspecファイルも修正。
=> [WIP]サインアップ画面修正

Capfile, config/deploy.rb, config/unicorn.rb
=> デプロイerror検証中

app/assets/stylesheets/sign_up/_sign_up.scss, app/controllers/application_controller.rb, app/controllers/purchase_controller.rb, app/controllers/signup_controller.rb, app/controllers/users_controller.rb, app/models/item.rb, app/models/user.rb, app/views/devise/registrations/new.html.haml, app/views/purchase/done.html.haml, app/views/purchase/show.html.haml, app/views/signup/step3.html.haml, config/locales/ja.yml, db/migrate/20191005101419_add_details_to_users.rb, db/migrate/20191005115601_change_data_postal_code_to_users.rb, db/schema.rb
=> [WIP]User shipping stasus

app/controllers/items_controller.rb
商品詳細で、前の商品を見に行こうとすると、一番最初の商品を見に行っているのを修正。
=> [WIP]item_show_back_fix
